### ISSUE TITLE
Volunteer Group Chat throwing error. Volunteer Groups won't load

### ISSUE THREAD

**Issue by asleepingpanda** [christfellowshipchurch/apollos-api#194]
The following error is being thrown on the API when attempting to load Volunteer Groups on the app:

```
StreamChat error code 4: GetOrCreateChannel failed with error: "Duplicate members passed to get or create channel, only send 1 member once"
```

This error is causing for Volunteer Groups to _not load_ on the mobile app. This was confirmed by the following steps:
1. Load local dev environment with API and Mobile App
2. Load a Volunteer Group on the Profile Page
3. _See Error_
4. Set the `GROUP_CHAT` feature flag on API to `disabled`
5. Reload the Volunteer Group
6. _No Error_

**Comment by rkdavidson** [comment]
Note to self: should we just quickly de-dupe the IDs prior to Stream calls?
