### ISSUE TITLE
Perform a one-off hard data sync

### ISSUE THREAD

**Issue by drewbarontini** [christfellowshipchurch/apollos-api#230]
Run a one-off hard data sync with Rock and Algolia so that we're ready for launch.

**Comment by rkdavidson** [comment]
The mechanism for this currently is here:
https://github.com/christfellowshipchurch/apollos-api/blob/master/src/data/group-item/data-source.js#L1277

It needs cleaned up, but the bones are in place.

It uses a hard coded list of `sampleGroupIds` that I pulled from Rock's group finder. This should be some Rock query to find searchable non-private (etc) groups.

There's some arbitrary (and temporary) safety mechanisms that can be removed. The intention was to prevent accidental abuse to Rock during development by adding friction and chunking out the overall processing load.

**Comment by rkdavidson** [comment]
This was done for GF launch, and the automatic data syncing in working shape, too.
