### ISSUE TITLE
Provide mechanism to sync a group

### ISSUE THREAD

**Issue by drewbarontini** [christfellowshipchurch/apollos-api#231]
Add a mutation that will allow syncing a single Group (using the Rock Group ID) with Algolia.

**Comment by rkdavidson** [comment]
**Schema:**
```mutation indexGroup(id: String, action: INDEX_ACTION, key: String): String```
https://github.com/christfellowshipchurch/apollos-api/blob/master/src/data/search/schema.js#L46-L47

**Data Source Method:**
https://github.com/christfellowshipchurch/apollos-api/blob/master/src/data/group-item/data-source.js#L1258

**Comment by jordanwade** [comment]
Looks done to me! Closing
