### ISSUE TITLE
Group chat channel muteNotifications field gets reset/dropped

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/apollos-api#235]
I believe there is a problem with the notification bell on the mobile app group chat. I can't remember the details of user reported behavior, but looking through the code for #233 made me realize the field may be getting dropped occasionally due to our abstraction `getChannel`.

**Comment by rkdavidson** [comment]
@asleepingpanda I think this is safe to close now, but leave it up to you as I think we're still experiencing some bugginess with the notification muting behavior on mobile app?

**Comment by asleepingpanda** [comment]
Yeah I'm good to close this! It's being tracked inside of Jira
